services:

  mysqldb:
    image: mysql:5.7
    volumes:
      - db_data_logger:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: logger
      MYSQL_USER: logger
      MYSQL_PASSWORD: logger
    ports:
      - 3306:3306

  logger:
    depends_on:
      - mysqldb
    image: sbdi/logger-dev
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./sbdi/data/config/logger-config.properties:/data/logger/config/logger-config.properties

volumes:
  db_data_logger:
#  db_data_logger_prod:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: "/home/mats/Documents/sbdi/logger/db_data_logger"
